### ISSUE TITLE
take a look at this kernel

### ISSUE THREAD

**Issue by ghost** [XePeleato/ALE-L21_ESAL#1]
can you take a look at russian custom kernel which is very performance i would love to see something as good as it for marshmallow (this one is for lollipop :( )
http://4pda.ru/forum/index.php?showtopic=670410&st=3740#entry44617209

**Comment by XePeleato** [comment]
@DyWN The 6.0 kernel release left some important drivers out. I won't add new stuff until the basic functionality is covered, but thanks, I'll check it out!
